### PR TITLE
WIP: Conversion to Facade

### PR DESCRIPTION
**Pull request by LJBD**
I've prepared a new version of this DS based on [facadedevice](https://github.com/MaxIV-KitsControls/tango-facadedevice/).

The short summary of what I've done:
1. I've configured proxy attributes for beam current, lifetime and energy.
2. I've configured combined attributes (with expert visibility) for lists of pressures: from dipole sections and from straight sections.
3. I've created logical attributes for all average pressures, average pressures divided by current and other similar things.
4. I've refactored the package - it was based on a POGO PythonHL schema and now it's a little bit more readable.
5. I've tried subclassing `combined_attribute` to add a descriptions field to it - I haven't tested that yet.

The only issue left for me to handle is how to get a description of a location where we have maximum pressure. In the old version of the DS I had 2 properties with lists of attributes and after each attribute I had a semicolon followed by a description. I want to keep that also in the new version.
I've tried parsing such a property so I've created a [subclass](https://github.com/synchrotron-solaris/dev-solaris-vacuumparameters/blob/facade_conversion/VacuumParameters/utils.py#L8) of combined attribute and in its configure_binding method I've added some code for doing that.
I assumed that the order in which you put attributes in the property for a combined attribute is preserved – is that really the case?

I've left old method for reading MaxPressureLocation in the device class just not to forget to convert it.

### CODE REVIEW

**Comment by LJBD** [comment]
@vxgmichel - I've tried mailing you, but your mailing server rejects my messages.
When you were here at the PyTango workshop, I mentioned that I will present a DS on Tango Meeting and I want to convert it to Façade. I’ve had some time this week and I’ve done most of the conversion, but I have a request: could you please review it?

**Comment by vxgmichel** [comment]
Hi Łukasz,

I won't have time to review your code until next week, but I had a quick look and it seems like a great use case for the facade lib!

 I have one comment about `CombinedAttrWithDesc`: you might want to consider a simpler approach. The property used by  `combined_attribute` doesn't have to be a tango device property, it can also be a python property. So you should be able to do something like that:

```
    @property
    def SomeDescriptions(self):
       return [line.split(';')[1] for line in self.SomeTangoDeviceProperty]

    @property
    def SomeAttributes(self):
       return [line.split(';')[0] for line in self.SomeTangoDeviceProperty]

    @combined_attribute(
        property_name='SomeAttributes'
        [...]
```

**Comment by LJBD** [comment]
>  it can also be a python property
Oh, I didn't know that, that might really simplify things - thanks!

I've refactored it a bit so that now I use `description` field of your Node class to store those descriptions. Then, I obtain all subnodes of my combined attributes and get the description of the one with the highest value.

**Comment by LJBD** [comment]
It seems that the segmentation fault doesn't show up when all attributes can be read correctly (when I tested this previously, beam lifetime was switched on and off continuously as the operators were injecting and killing the beam many times in a row).
One more thing regarding the `CombinedAttrWithDesc`: the way I do it now ensures that I will always get a correct description, even when the order of the attributes in a combined attribute is not preserved exactly from the corresponding property.

**Comment by vxgmichel** [comment]
> It seems that the segmentation fault doesn't show up when all attributes can be read correctly (when I tested this previously, beam lifetime was switched on and off continuously as the operators were injecting and killing the beam many times in a row).

Let me know if you manage to reproduce it, I'm very interested in knowing what caused this segfault.

> One more thing regarding the CombinedAttrWithDesc: the way I do it now ensures that I will always get a correct description, even when the order of the attributes in a combined attribute is not preserved exactly from the corresponding property.

The order should be preserved anyway since `get_combined_results` returns an `OrderedDict`.

**Comment by LJBD** [comment]
> The order should be preserved anyway since get_combined_results returns an OrderedDict.

All right, so that should be it. That means that my implementation is needlessly complicated, but it works so I won't change it before Tango Meeting.

**Pull request merged**
